# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge
org.gradle.parallel=true


mod_version=1.6.3
mod_id=extendedae_plus
mod_name=ExtendedAE-Plus
maven_group = com.extendedae_plus
archives_name = extendedae_plus

# Minecraft properties
minecraft_version=1.20.1
mod_loader=forge

# Dependencies
forge_version = 1.20.1-47.4.3
glodium_version=5006780
ae2_version=15.4.10
guideme_version=20.1.7
wireless_terminals_version=5162352
jei_version=15.49.0.188
applied_flux_version=5329825
mega_cells_version=5320730
jade_version=4768593
basic_math_version=0.6.1
architectury_version=5137938
rei_version=12.0.622
cloth_config_version=9.0.94
projecte_version=4901949
appliede_version=5364294
gregtech_version=5369020
ldlib_version=5394816
ie_version=5224387
mixin_version=0.8.4
curios_version=6418456

# EMI for recipe viewer switch (use_Xei = emi | jei | emi_jei)
emi_version=1.1.19+1.20.1
use_Xei=jei
